### ISSUE TITLE
Version update notifications for clients and servers

### ISSUE THREAD

**Issue by rvstwi** [OpenRVS-devs/OpenRVS#20]
I'd like to have some sort of simple alert for both clients and servers when their version is out of date.  For clients, a simple prompt pop-up window in the multiplayer menu would work.  Servers - probably a log notification or a console alert for administrator players.

For this to work, we'd need a hosted text document that has the current latest release.  OpenRVS should connect to this doc once to read the version number, and compare against an internal variable.  We could have strings for what the update would include as well.

EG: Popup reads: "Your version of the OpenRVS patch is out of date.  The latest version is v1.54, and adds support for: ping display in menus, sorting servers by ping.  Visit rvsgaming.org for the latest patch."

I wish I'd started this before, because if we plan to switch to CSV or do other major updates, it would have been nice to have the majority of players already have a built in system to notify of updates.

**Comment by ijemafe** [comment]
Can get latest version from the `tag_name` field here: https://api.github.com/repos/OpenRVS-devs/OpenRVS/releases/latest

**Comment by rvstwi** [comment]
We'll need to implement an internal variable for version to compare against the most updated version number we fetch from online.

We can also add a link that goes directly to the latest version download page.

**Comment by rvstwi** [comment]
Latest PR has functionality for client pop-up to alert of version mismatches.
