### ISSUE TITLE
Add support for CSV-formatted server lists

### ISSUE THREAD

**Issue by rvstwi** [OpenRVS-devs/OpenRVS#3]
OpenServerList.uc currently assumes that text files it connects to are formatted like an Unreal config INI, and parses text looking for specific words and symbols with that assumption.

We should add support in that class for detection and parsing of a CSV-formatted server list text file.

IMPORTANT: Compatibility MUST be maintained with older versions, so the INI parser will need to stay.  Code should be able to detect INI or CSV format, then parse accordingly.

Giving ourselves the option for CSV format in the future will mean that a greater range of software can interact with a hosted server list, hopefully opening up more possibilities.

**Comment by rvstwi** [comment]
https://github.com/rvstwi/OpenRVS/pull/15#  ijemafe got us started, by improving the current parser.

Note that we'll have to start by re-figuring what the hell we're doing in event Closed() in OpenServerList.uc.  See issue #17 as well for a to-do when we fight with this one.

**Comment by rvstwi** [comment]
#18 improves the above issue (event Closed()).  CSV parser should be a simple addition now.  If we officially move to CSV format, we'll need to support both formats for a while and give people lots of chances to update.

**Comment by rvstwi** [comment]
We should ensure before writing a parser that we actually agree upon the specifics of the CSV format we want to use.  Eg is first line categories? (Server name,Server IP,Server mode) or do we start first line is first server?  What do we enclose in quotes and what do we not?

**Comment by ijemafe** [comment]
> We should ensure before writing a parser that we actually agree upon the specifics of the CSV format we want to use. Eg is first line categories? (Server name,Server IP,Server mode) or do we start first line is first server? What do we enclose in quotes and what do we not?

Agreed on coming up with the design before the implementation. For context, CSV is defined in RFC 4180. There is a summary here: https://en.wikipedia.org/wiki/Comma-separated_values#RFC_4180_standard

My votes are YES to optional header and NO to quoted fields.

**Comment by rvstwi** [comment]
Agreed with both header and quoted fields.  It would also be nice to have the parser intelligently use the header to determine order of fields for the file.  So it doesn't matter if a server list host does
name,ip,port,mode
or
port,name,mode,ip
or whatever, we can still parse no problem.
